server:
  port: 80
spring:
  datasource:
    username: k2sql
    password: k2sql@123
    url: jdbc:sqlserver://192.168.0.107\k2;database=chint.oa.workflow.lvElecCenter
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  resources:
    static-locations: classpath:/File/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzb.entity
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql